#pragma once

#define ONESHOT_TIMEOUT 100
#define TAPPING_TERM 150
/* #define PERMISSIVE_HOLD */
#define HOLD_ON_OTHER_KEY_PRESS
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD_PER_KEY
#define COMBO_PROCESS_KEY_RELEASE
#define COMBO_TERM 25
#define COMBO_ONLY_FROM_LAYER 0

#ifdef AUDIO_ENABLE
    #define STARTUP_SONG SONG(PLANCK_SOUND)
    // #define STARTUP_SONG SONG(NO_SOUND)

    #define DEFAULT_LAYER_SONGS { SONG(QWERTY_SOUND), \
                                  SONG(COLEMAK_SOUND), \
                                  SONG(DVORAK_SOUND) \
                                }
#endif

/*
 * MIDI options
 */

/* Prevent use of disabled MIDI features in the keymap */
//#define MIDI_ENABLE_STRICT 1

/* enable basic MIDI features:
   - MIDI notes can be sent when in Music mode is on
*/

/* #define MIDI_BASIC */

/* enable advanced MIDI features:
   - MIDI notes can be added to the keymap
   - Octave shift and transpose
   - Virtual sustain, portamento, and modulation wheel
   - etc.
*/
//#define MIDI_ADVANCED

/* override number of MIDI tone keycodes (each octave adds 12 keycodes and allocates 12 bytes) */
//#define MIDI_TONE_KEYCODE_OCTAVES 2

// Most tactile encoders have detents every 4 stages
#define ENCODER_RESOLUTION 4

// Settings for making tap-keys more reliable when typing fast
/* #define PERMISSIVE_HOLD */
/* #define IGNORE_MOD_TAP_INTERRUPT */

/* Disable unnecessary animations */
#undef  ENABLE_RGB_MATRIX_ALPHAS_MODS
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#undef  ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#undef  ENABLE_RGB_MATRIX_BREATHING
#undef  ENABLE_RGB_MATRIX_BAND_SAT
#undef  ENABLE_RGB_MATRIX_BAND_VAL
#undef  ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#undef  ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#undef  ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#undef  ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#undef  ENABLE_RGB_MATRIX_CYCLE_ALL
#undef  ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#undef  ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#undef  ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#undef  ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#undef  ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#undef  ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#undef  ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#undef  ENABLE_RGB_MATRIX_DUAL_BEACON
#undef  ENABLE_RGB_MATRIX_RAINBOW_BEACON
#undef  ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#undef  ENABLE_RGB_MATRIX_RAINDROPS
#undef  ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#undef  ENABLE_RGB_MATRIX_HUE_BREATHING
#undef  ENABLE_RGB_MATRIX_HUE_PENDULUM
#undef  ENABLE_RGB_MATRIX_HUE_WAVE
#undef  ENABLE_RGB_MATRIX_PIXEL_RAIN
#undef  ENABLE_RGB_MATRIX_PIXEL_FLOW
#undef  ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#undef  ENABLE_RGB_MATRIX_TYPING_HEATMAP
#undef  ENABLE_RGB_MATRIX_DIGITAL_RAIN
#undef  ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#undef  ENABLE_RGB_MATRIX_SOLID_REACTIVE
#undef  ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#undef  ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#undef  ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#undef  ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#undef  ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#undef  ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#undef  ENABLE_RGB_MATRIX_SPLASH
#undef  ENABLE_RGB_MATRIX_MULTISPLASH
#undef  ENABLE_RGB_MATRIX_SOLID_SPLASH
#undef  ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
